# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tue1fuTb7j7yWYsCg1sp-rwDZrilZNzX
"""

!pip install catboost

!pip install javalang
!pip install tree-sitter==0.21.3 tree-sitter-languages==1.10.2

# -*- coding: utf-8 -*-

import os
import json
import warnings
import numpy as np
import pandas as pd
from pathlib import Path

warnings.filterwarnings("ignore")

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report,
)

# Import everything we need from the training module
from catboost_unified import (
    UnifiedCodeDetector,
    get_languages_from_df,
    build_feature_matrix_unified,
    normalise_language,
)


MODEL_DIR = ""

OUTPUT_DIR = "./catboost_inference_results"


DATASETS = [
    # Dataset 1: Unseen Domains 
    {
        "name": "Unseen Domains",
        "source": "csv",
        "path":  "unseen_domains_dataset.csv",
        "code_col": "code",
        "label_col": "target",
        "label_map": {"human": 0, "llm": 1},
        "force_unknown":  False,
    },

    {
        "name": "Unseen Programming Languages",
        "source": "jsonl",
        "path": "unseen_lang_dataset.jsonl",
        "code_col": "code",
        "label_col": "label",
        "label_map": {"human": 0, "llm": 1},
        "force_unknown":  True,
    },
    # Dataset 3: Unseen Models (dual JSONL)
    {
        "name":  "Unseen Models",
        "source": "dual_jsonl",
        "path": "unseen_models_dataset.jsonl",
        "meta_cols":  ["id", "problem_number", "language", "difficulty",
                           "generator_name", "generator_type"],
        "force_unknown":  False,
    },
]


os.makedirs(OUTPUT_DIR, exist_ok=True)


# Dataset loaders 

def load_dual_jsonl(cfg: dict) -> pd.DataFrame:
   
    with open(cfg["path"]) as f:
        raw = json.load(f)

    meta_cols = cfg.get(
        "meta_cols",
        ["id", "problem_number", "language", "difficulty",
         "generator_name", "generator_type"],
    )

    rows = []
    for entry in raw:
        base = {col: entry.get(col) for col in meta_cols if col in entry}
        rows.append({**base, "code": entry["human_generated_code"],
                     "code_type": "human",  "_label_int": 0})
        rows.append({**base, "code": entry["ai_generated_code"],
                     "code_type": "machine", "_label_int": 1})

    df = pd.DataFrame(rows).reset_index(drop=True)
    print(f"  Expanded {len(raw)} problems → {len(df)} rows "
          f"({len(raw)} human + {len(raw)} machine)")
    return df


def load_dataframe(cfg: dict) -> pd.DataFrame:
    src = cfg["source"]

    if src == "dual_jsonl":
        return load_dual_jsonl(cfg)

    if src == "csv":
        df = pd.read_csv(cfg["path"])
    elif src == "jsonl":
        df = pd.read_json(cfg["path"], lines=True)
    else:
        raise ValueError(f"Unknown source type: {src!r}")

    # Normalise label column
    lc = cfg.get("label_col")
    lm = cfg.get("label_map", {})
    if lc and lc in df.columns:
        if lm:
            df["_label_int"] = df[lc].map(lm)
            unmapped = df["_label_int"].isna().sum()
            if unmapped:
                print(f"  ⚠  {unmapped} rows had unmapped labels "
                      f"and will be excluded from metrics.")
        else:
            df["_label_int"] = df[lc].astype(int)
    else:
        df["_label_int"] = np.nan   # no ground truth

    return df


# Metrics helper 

def compute_metrics(y_true, y_pred) -> dict:
    return {
        "precision": round(precision_score(y_true, y_pred, average="macro",
                                           zero_division=0) * 100, 2),
        "recall":    round(recall_score   (y_true, y_pred, average="macro",
                                           zero_division=0) * 100, 2),
        "f1":        round(f1_score       (y_true, y_pred, average="macro",
                                           zero_division=0) * 100, 2),
        "accuracy":  round(accuracy_score (y_true, y_pred) * 100, 2),
    }


def print_metrics_table(metrics: dict, n: int, title: str = ""):
    if title:
        print(f"\n  {title} ({n:,} rows):")
    print(f"    P={metrics['precision']:.2f}%  R={metrics['recall']:.2f}%  "
          f"F1={metrics['f1']:.2f}%  Acc={metrics['accuracy']:.2f}%")


# Language resolver 

def resolve_languages(df: pd.DataFrame, force_unknown: bool) -> list:
    
    if force_unknown:
        print("  [language] force_unknown=True → all rows set to 'unknown' "
              "(stat features only, no AST)")
        return ["unknown"] * len(df)
    return get_languages_from_df(df)


# Main inference loop 

def main():
    # Load model
    model_path   = os.path.join(MODEL_DIR, "catboost_unified.cbm")
    feat_names_p = os.path.join(MODEL_DIR, "feature_names.json")
    feat_mask_p  = os.path.join(MODEL_DIR, "feat_mask.npy")

    for p in [model_path, feat_names_p, feat_mask_p]:
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"Required file not found: {p}\n"
                f"Set MODEL_DIR to the folder produced by catboost_unified.py training."
            )

    print(f"Loading CatBoost model from: {MODEL_DIR}")
    detector = UnifiedCodeDetector(model_path, feat_names_p, feat_mask_p)
    print("  ✓ Model loaded\n")

    all_results = {}

    for ds_cfg in DATASETS:
        ds_name = ds_cfg["name"]
        print(f"\n{'='*65}")
        print(f"  DATASET : {ds_name}")
        print(f"{'='*65}")

        # Load data
        try:
            df = load_dataframe(ds_cfg)
        except Exception as e:
            print(f"  ✗ Failed to load dataset: {e}")
            all_results[ds_name] = {"error": str(e)}
            continue

        print(f"  Rows loaded: {len(df):,}")

        # dual_jsonl always uses "code"; others use config
        code_col = ("code" if ds_cfg["source"] == "dual_jsonl"
                    else ds_cfg.get("code_col", "code"))

        if code_col not in df.columns:
            msg = (f"Column '{code_col}' not found. "
                   f"Available: {list(df.columns)}")
            print(f"  ✗ {msg}")
            all_results[ds_name] = {"error": msg}
            continue

        # Resolve languages 
        force_unknown = ds_cfg.get("force_unknown", False)
        languages = resolve_languages(df, force_unknown)

        # Feature extraction + inference
        codes = df[code_col].fillna("").tolist()
        feat_col = ds_cfg.get("feat_col", None)
        precomp  = (df[feat_col].tolist() if feat_col and feat_col in df.columns
                    else [{}] * len(df))

        X, _, _, used_langs = build_feature_matrix_unified(
            codes, precomp,
            languages=languages,
            known_mask=detector.feat_mask,
            verbose=True,
        )
        preds = detector.model.predict(X).astype(int)

        # Build output DataFrame 
        out_df = df.copy()
        out_df["pred_label"]    = preds
        out_df["pred_class"]    = np.where(preds == 0, "human", "machine")
        out_df["used_language"] = used_langs

        # Save predictions
        safe_name = ds_name.lower().replace(" ", "_")
        pred_path = os.path.join(OUTPUT_DIR, f"catboost_{safe_name}_predictions.csv")
        out_df.to_csv(pred_path, index=False)
        print(f"  ✓ Predictions saved → {pred_path}")

        #  Overall metrics 
        y_true  = df["_label_int"].values if "_label_int" in df.columns else np.full(len(df), np.nan)
        labelled_mask = ~pd.isna(y_true)
        n_labelled = labelled_mask.sum()
        metrics = None

        if n_labelled > 0:
            yt = y_true[labelled_mask].astype(int)
            yp = preds[labelled_mask]
            metrics = compute_metrics(yt, yp)
            print_metrics_table(metrics, int(n_labelled), "Overall metrics")
            print()
            print(classification_report(
                yt, yp,
                target_names=["human (0)", "machine (1)"],
                digits=4,
            ))
        else:
            print("  No ground-truth labels — skipping metrics.")

        #  Per-language breakdown 
        lang_metrics = {}
        lang_col_in_df = next(
            (c for c in ["language", "lang", "programming_language", "_lang"]
             if c in out_df.columns),
            None,
        )

        if lang_col_in_df and not force_unknown:
            print(f"  ── Per-language breakdown ──")
            print(f"  {'Language':14}  {'P':>8}  {'R':>8}  {'F1':>8}  "
                  f"{'Acc':>8}  {'N':>6}")
            print(f"  {'-'*58}")
            for lang in sorted(out_df[lang_col_in_df].dropna().unique()):
                mask = (out_df[lang_col_in_df] == lang).values
                yt_l = y_true[mask]
                yp_l = preds[mask]
                valid = ~pd.isna(yt_l)
                if valid.sum() == 0:
                    continue
                lm = compute_metrics(yt_l[valid].astype(int), yp_l[valid])
                lang_metrics[lang] = lm
                print(f"  {str(lang):14}  {lm['precision']:>8.2f}  "
                      f"{lm['recall']:>8.2f}  {lm['f1']:>8.2f}  "
                      f"{lm['accuracy']:>8.2f}  {int(valid.sum()):>6}")

        # Extra breakdowns for dual_jsonl
        gen_metrics  = {}
        diff_metrics = {}

        if ds_cfg["source"] == "dual_jsonl":

            # Per-generator (machine rows only)
            if "generator_name" in out_df.columns:
                machine_df = out_df[out_df["code_type"] == "machine"]
                print(f"\n  ── Per-generator breakdown (machine rows only) ──")
                print(f"  {'Generator':24}  {'P':>8}  {'R':>8}  {'F1':>8}  "
                      f"{'Acc':>8}  {'N':>5}")
                print(f"  {'-'*64}")
                for gen in sorted(machine_df["generator_name"].dropna().unique()):
                    mask = (machine_df["generator_name"] == gen).values
                    yt_g = machine_df["_label_int"].values[mask]
                    yp_g = machine_df["pred_label"].values[mask]
                    valid = ~pd.isna(yt_g)
                    if valid.sum() == 0:
                        continue
                    gm = compute_metrics(yt_g[valid].astype(int), yp_g[valid])
                    gen_metrics[gen] = gm
                    print(f"  {str(gen):24}  {gm['precision']:>8.2f}  "
                          f"{gm['recall']:>8.2f}  {gm['f1']:>8.2f}  "
                          f"{gm['accuracy']:>8.2f}  {int(valid.sum()):>5}")

            # Per-difficulty
            if "difficulty" in out_df.columns:
                print(f"\n  ── Per-difficulty breakdown ──")
                print(f"  {'Difficulty':12}  {'P':>8}  {'R':>8}  {'F1':>8}  "
                      f"{'Acc':>8}  {'N':>6}")
                print(f"  {'-'*58}")
                for diff in ["easy", "medium", "hard"]:
                    mask = (out_df["difficulty"] == diff).values
                    yt_d = y_true[mask]
                    yp_d = preds[mask]
                    valid = ~pd.isna(yt_d)
                    if valid.sum() == 0:
                        continue
                    dm = compute_metrics(yt_d[valid].astype(int), yp_d[valid])
                    diff_metrics[diff] = dm
                    print(f"  {diff:12}  {dm['precision']:>8.2f}  "
                          f"{dm['recall']:>8.2f}  {dm['f1']:>8.2f}  "
                          f"{dm['accuracy']:>8.2f}  {int(valid.sum()):>6}")

        all_results[ds_name] = {
            "n_rows":        len(df),
            "n_labelled":    int(n_labelled),
            "force_unknown": force_unknown,
            "metrics":       metrics,
            "per_language":  lang_metrics,
            "per_generator": gen_metrics,
            "per_difficulty": diff_metrics,
            "pred_file":     pred_path,
        }

    # Save summary JSON 
    summary_path = os.path.join(OUTPUT_DIR, "catboost_inference_summary.json")
    with open(summary_path, "w") as f:
        json.dump(all_results, f, indent=2)

    print("\n")
    print(f"  All done!")
    print(f"  Summary        → {summary_path}")
    print(f"  Per-dataset predictions in: {os.path.abspath(OUTPUT_DIR)}/")


if __name__ == "__main__":
    main()
