# -*- coding: utf-8 -*-
"""FastDetect_Basline1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-ggFkn0teb061oHpWy3v0wzeCSkP24-
"""

CHUNK_INDEX = 0
TOTAL_CHUNKS = 5

!pip install datasets transformers torch scikit-learn tqdm pandas
!git clone https://github.com/baoguangsheng/fast-detect-gpt.git

from datasets import load_dataset
import pandas as pd
import numpy as np

print("Downloading CoDet-M4 dataset from Hugging Face...")
dataset = load_dataset("DaniilOr/CoDET-M4")

train_df = dataset['train'].to_pandas()
train_df['label'] = train_df['target'].apply(lambda x: 1 if x == 'ai' else 0)
chunks = np.array_split(train_df, TOTAL_CHUNKS)
eval_df = chunks[CHUNK_INDEX].copy()
code_col = 'cleaned_code'
print(f"Processing CHUNK {CHUNK_INDEX + 1}/{TOTAL_CHUNKS} with {len(eval_df)} codes for evaluation.")

import sys
import os
import torch
from tqdm import tqdm

repo_scripts_path = os.path.abspath('fast-detect-gpt/scripts')
if repo_scripts_path not in sys.path:
    sys.path.append(repo_scripts_path)

from model import load_tokenizer, load_model
from fast_detect_gpt import get_sampling_discrepancy_analytic

device = "cuda" if torch.cuda.is_available() else "cpu"

model_name = "EleutherAI/gpt-neo-125m"
print(f"Loading tokenizer and model: {model_name}...")
tokenizer = load_tokenizer(model_name, "xsum")
model = load_model(model_name, device, cache_dir="./cache")
model.eval()

# ANALYTICAL FUNCTION WRAPPER
def get_fast_detect_score(text):
    if not isinstance(text, str) or len(text.strip()) == 0:
        return None

    tokenized = tokenizer(
        text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512,
        return_token_type_ids=False
    ).to(device)
    if tokenized.input_ids.size(1) < 2:
        return None

    labels = tokenized.input_ids[:, 1:]

    with torch.no_grad():
        logits = model(**tokenized).logits[:, :-1]
        # Fast-DetectGPT uses a reference model (to sample) and a scoring model (to score).
        logits_ref = logits
        logits_score = logits
        try:
            discrepancy = get_sampling_discrepancy_analytic(logits_ref, logits_score, labels)
            return float(discrepancy)
        except Exception as e:
            return None

from google.colab import drive
import gc

drive.mount('/content/drive')
output_filename = f'/content/drive/MyDrive/codet_m4_chunk_{CHUNK_INDEX}_results.csv'

if 'fast_detect_score' not in eval_df.columns:
    eval_df['fast_detect_score'] = np.nan

if os.path.exists(output_filename):
    print(f"Found existing save at {output_filename}. Resuming...")
    saved_df = pd.read_csv(output_filename)
    eval_df.update(saved_df[['fast_detect_score']])

unscored_indices = eval_df[eval_df['fast_detect_score'].isna()].index
print(f"Remaining rows to score in Chunk {CHUNK_INDEX}: {len(unscored_indices)}")

cols_to_drop = ['code', 'text', 'prompt', 'cleaned_code']
save_cols = [col for col in eval_df.columns if col not in cols_to_drop]

SAVE_INTERVAL = 10000
for i, idx in enumerate(tqdm(unscored_indices, desc=f"Running Fast-DetectGPT on Chunk {CHUNK_INDEX}")):
    code_snippet = eval_df.loc[idx, code_col]
    eval_df.loc[idx, 'fast_detect_score'] = get_fast_detect_score(code_snippet)

    if (i + 1) % SAVE_INTERVAL == 0:
        eval_df[save_cols].to_csv(output_filename, index=False)
        torch.cuda.empty_cache()
        gc.collect()

eval_df[save_cols].to_csv(output_filename, index=False)
print(f"Chunk {CHUNK_INDEX} processing complete!")
eval_df = eval_df.dropna(subset=['fast_detect_score'])

import pandas as pd
import numpy as np
import os
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from google.colab import drive

folder_path = '/content/drive/MyDrive/FastDetect/chunk_results'
file_names = ['0.csv', '1.csv', '2.csv', '3.csv', '4.csv']

print("Loading and merging CSV chunks...")
df_list = []
for file_name in file_names:
    file_path = os.path.join(folder_path, file_name)
    if os.path.exists(file_path):
        df_list.append(pd.read_csv(file_path))
        print(f"  - Loaded {file_name}")
    else:
        print(f"Warning: Could not find {file_path}")

eval_df = pd.concat(df_list, axis=0, ignore_index=True)
eval_df = eval_df.dropna(subset=['fast_detect_score'])
print(f"\nSuccessfully merged! Total evaluated rows: {len(eval_df)}")

# Fast-DetectGPT requires the median score of the ENTIRE dataset to act as the threshold
global_threshold = np.median(eval_df['fast_detect_score'])
eval_df['prediction'] = (eval_df['fast_detect_score'] > global_threshold).astype(int)

if 'source' in eval_df.columns:
    eval_df['source_clean'] = eval_df['source'].astype(str).str.title()
if 'language' in eval_df.columns:
    eval_df['language_clean'] = eval_df['language'].astype(str).str.upper()


def print_breakdown_table(dataframe, column_name, table_title):
    print("\n" + "="*85)
    print(f"📊 {table_title}")
    print("="*85)
    print(f"{column_name.capitalize():<15} | {'AUROC':<8} | {'Precision':<9} | {'Recall':<8} | {'F1 Score':<8} | {'Accuracy':<8}")
    print("-" * 85)

    unique_vals = dataframe[column_name].dropna().unique()
    for val in sorted(unique_vals):
        subset = dataframe[dataframe[column_name] == val]

        if len(subset) > 0 and len(subset['label'].unique()) > 1:
            auroc = roc_auc_score(subset['label'], subset['fast_detect_score'])
            acc = accuracy_score(subset['label'], subset['prediction'])
            prec = precision_score(subset['label'], subset['prediction'], zero_division=0)
            rec = recall_score(subset['label'], subset['prediction'], zero_division=0)
            f1 = f1_score(subset['label'], subset['prediction'], zero_division=0)

            print(f"{str(val):<15} | {auroc:<8.4f} | {prec:<9.4f} | {rec:<8.4f} | {f1:<8.4f} | {acc:<8.4f}")
    print("="*85)


print("\n" + "="*85)
print("OVERALL FAST-DETECTGPT BASELINE RESULTS")
print("="*85)
overall_auroc = roc_auc_score(eval_df['label'], eval_df['fast_detect_score'])
overall_acc = accuracy_score(eval_df['label'], eval_df['prediction'])
overall_prec = precision_score(eval_df['label'], eval_df['prediction'], zero_division=0)
overall_rec = recall_score(eval_df['label'], eval_df['prediction'], zero_division=0)
overall_f1 = f1_score(eval_df['label'], eval_df['prediction'], zero_division=0)

print(f"AUROC      : {overall_auroc:.4f}")
print(f"Precision  : {overall_prec:.4f}")
print(f"Recall     : {overall_rec:.4f}")
print(f"F1 Score   : {overall_f1:.4f}")
print(f"Accuracy   : {overall_acc:.4f}")
print("="*85)

if 'language_clean' in eval_df.columns:
    print_breakdown_table(eval_df, 'language_clean', "RESULTS BY PROGRAMMING LANGUAGE")
else:
    print("\nError: 'language' column not found in the dataset.")

if 'source_clean' in eval_df.columns:
    print_breakdown_table(eval_df, 'source_clean', "RESULTS BY DATA SOURCE")
else:
    print("\nError: 'source' column not found in the dataset.")